In [1]:
import numpy as np

In [2]:
from sympy import *

In [3]:
w0 = Symbol('w0')
w1 = Symbol('w1')
w2 = Symbol('w2')

In [4]:
a = np.array([[0,3,0],
              [1,2,1],
              [2,1,0],
              [3,0,3]])

In [5]:
print(a)

[[0 3 0]
 [1 2 1]
 [2 1 0]
 [3 0 3]]


In [51]:
print(f)

w0**2 + w1**2 + w2**2 + (w0 + 3*w2)**2 + (w0 + 2*w1 + w2)**2 + (w0 + 3*w1 - 3)**2 + (w0 + w1 + 2*w2 - 1)**2


In [52]:
f += w1**2 + w2**2 + w0**2

In [53]:
f0prime = f.diff(w0)
f1prime = f.diff(w1)
f2prime = f.diff(w2)

In [54]:
print(f0prime)
print(f1prime)
print(f2prime)

12*w0 + 12*w1 + 12*w2 - 8
12*w0 + 32*w1 + 8*w2 - 20
12*w0 + 8*w1 + 32*w2 - 4


In [64]:
m1 = np.array([[10.,12.,12.],
               [12.,30.,8.],
               [12.,8.,30.]])
v1 = np.array([8.,20.,4.])

In [65]:
b = np.linalg.solve(m1, v1)

In [72]:
for i in range(len(b)):
    print('w' + str(i) +' = ' + str(round(b[i],2)))

w0 = 0.17
w1 = 0.62
w2 = -0.1
